VISA = 4

MASTER = 5

m_COUNTRIES_ = {
    "Random": "0",
    "Albania": "al",
    "Algeria": "dz",
    "Argentina": "ar",
    "Armenia": "am",
    "Australia": "au",
    "Austria": "at",
    "Azerbaijan": "az",
    "Bahamas": "bs",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Bolivia": "bol",
    "Botswana": "bw",
    "Brazil": "br",
    "Brunei": "bn",
    "Cambodia": "kh",
    "Cameroun": "cm",
    "Canada": "ca",
    "Cayman Islands": "ky",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Cuba": "cu",
    "Cyprus": "cy",
    "Denmark": "dk",
    "Dominican Republic": "do",
    "DR Congo": "cd",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "Emirates": "ae",
    "Estonia": "ee",
    "Ethiopia": "et",
    "Fiji": "fj",
    "Finland": "fi",
    "France": "fr",
    "Germany": "de",
    "Ghana": "gh",
    "Guatemala": "gt",
    "Honduras": "hn",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "India": "in",
    "Indonesia": "id",
    "Iran": "ir",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Ivory Coast": "kt",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Korea": "ko",
    "Kuwait": "kw",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Lesotho": "ls",
    "Libya": "ly",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Madagascar": "mg",
    "Malawi": "mw",
    "Malaysia": "my",
    "Mali": "ml",
    "Malta": "mt",
    "Mauritius": "mu",
    "Mexico": "mx",
    "Moldova": "md",
    "Morocco": "ma",
    "Myanmar": "mm",
    "Namibia": "na",
    "Nepal": "np",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Nigeria": "ng",
    "Norway": "no",
    "Oman": "om",
    "Pakistan": "pk",
    "Panama": "pa",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portuguese": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Romania": "ro",
    "Russia": "ru",
    "Rwanda": "rw",
    "Saudi Arabia": "sa",
    "Senegal": "sn",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "South Africa": "za",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Suriname": "sr",
    "Sweden": "se",
    "Switzerland": "ch",
    "Taiwan(China)": "tw",
    "Tanzania": "tz",
    "Thailand": "th",
    "The Czech Republic": "cz",
    "The Republic of Iceland": "is",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Kingdom": "uk",
    "United States": "us",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Venezuela": "ve",
    "Vietnam": "vn",
    "Yemen": "ye",
    "Zambia": "zm",
    "Zimbabwe": "zw",
    "Киргизия": "kg"
}